# Managed by nixbox. Do not edit by hand.
{ pkgs, ... }:
{
  home.packages = [
    # nixbox:packages:start
    pkgs._1password-gui
    pkgs.bat
    pkgs.biome
    pkgs.brightnessctl
    pkgs.clang
    pkgs.codex
    pkgs.delta
    pkgs.devenv
    pkgs.discord
    pkgs.easyeffects
    pkgs.exfatprogs
    pkgs.eza
    pkgs.fd
    pkgs.fzf
    pkgs.gh
    pkgs.git
    pkgs.go
    pkgs.google-cloud-sdk
    pkgs.hunk
    pkgs.jdk
    pkgs.jq
    pkgs.jujutsu
    pkgs.just
    pkgs.kubectl
    pkgs.lmstudio
    pkgs.mission-center
    pkgs.mpv
    pkgs.nautilus
    pkgs.ncdu
    pkgs.obsidian
    pkgs.onlyoffice-desktopeditors
    pkgs.opencode
    pkgs.opencode-desktop
    pkgs.openssl
    pkgs.pavucontrol
    pkgs.podman
    pkgs.podman-desktop
    pkgs.python3
    pkgs.python3Packages.huggingface-hub
    pkgs.qbittorrent
    pkgs.ripgrep
    pkgs.rustup
    pkgs.sbctl
    pkgs.seahorse
    pkgs.t3code
    pkgs.terraform
    pkgs.thunderbird
    pkgs.tor-browser
    pkgs.typescript-go
    pkgs.unzip
    pkgs.uv
    pkgs.xh
    pkgs.xwayland-satellite
    pkgs.zed-editor-fhs
    pkgs.zellij
    pkgs.zoom-us
    # nixbox:packages:end
  ];
}
